### ISSUE TITLE
pip Command in README Should Be pip3 for MacOS and Linux

### ISSUE THREAD

**Issue by sentemon** [risknu/radist#1]
The current instructions in the README file use the pip command to install dependencies. On many MacOS and Linux systems, `pip` is associated with Python 2, whereas `pip3` is the correct command for Python 3. To avoid confusion and potential installation issues, the README should be updated to use `pip3`.
(соси)

**Comment by risknu** [comment]
I'll explain: if you use `venv` (Python virtual environment), both pip and pip3 will work for you. As we know, creating a `venv` is one of the first steps to take when starting a project or installation. It's also worth noting that you can make pip work in Linux/macOS as well. Cancelled

**Comment by Sheudz** [comment]
хуйня переделывай

**Comment by razenxc** [comment]
ты чо приколист
ты чо приколист
ты чо приколист
ты чо приколист

**Comment by Sheudz** [comment]
макось сюда не надо было преплетать, макосью только нелюди ебаные пользуються на них всем похуй
